In [1]:
import numpy as np

In [2]:
x = [1, 2, 3, 4, 5, 6]
y = [7, 8, 9, 10, 11, 12]
x + y

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [3]:
4 * x

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [4]:
x * y

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
xx = np.array(x)
xx

array([1, 2, 3, 4, 5, 6])

In [7]:
yy = np.array(y)
yy

array([ 7,  8,  9, 10, 11, 12])

In [8]:
xx + yy

array([ 8, 10, 12, 14, 16, 18])

In [10]:
333 * xx

array([ 333,  666,  999, 1332, 1665, 1998])

In [11]:
xx * yy

array([ 7, 16, 27, 40, 55, 72])

In [12]:
xx @ yy # скалярное произведение

217

In [13]:
np.sum(xx * yy)

217

In [14]:
x = np.arange(10**7)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [15]:
type(x)

numpy.ndarray

In [16]:
y = list(x)
type(y)

list

In [19]:
%%timeit
sum(y)

172 ms ± 6.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%%timeit
np.sum(x)

1.71 ms ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [21]:
np.random.rand(5)

array([0.57111443, 0.59998603, 0.74185812, 0.98426357, 0.93380531])

**Бонусная задача:** 

Я хочу посчитать евклидово расстояние между каждой строкой $A$ и между каждой строкой $B$

In [22]:
A = np.random.normal(size=(3,4))
B = np.random.normal(size=(3,4))
A, B

(array([[ 1.14582581, -1.14940945, -0.49673539, -1.47854015],
        [ 0.50301409, -1.50003522, -0.40356792,  0.9798549 ],
        [ 1.27464156, -0.83881745, -0.4142402 , -1.17077428]]),
 array([[ 1.68555454, -0.11793157,  0.29695597,  0.30790691],
        [-1.06703203,  0.02537137, -0.71166858,  0.69197942],
        [ 0.26867636,  1.20643682, -0.70228827, -0.122572  ]]))

In [27]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.27521269, 2.22928428, 2.52521895])

In [30]:
A[None,:,:] # список из 1 матрицы

array([[[ 1.14582581, -1.14940945, -0.49673539, -1.47854015],
        [ 0.50301409, -1.50003522, -0.40356792,  0.9798549 ],
        [ 1.27464156, -0.83881745, -0.4142402 , -1.17077428]]])

In [32]:
A[None,:,:].shape

(1, 3, 4)

In [33]:
A[:,:,None] # лист из 3 объектов размера 4 x 1 

array([[[ 1.14582581],
        [-1.14940945],
        [-0.49673539],
        [-1.47854015]],

       [[ 0.50301409],
        [-1.50003522],
        [-0.40356792],
        [ 0.9798549 ]],

       [[ 1.27464156],
        [-0.83881745],
        [-0.4142402 ],
        [-1.17077428]]])

In [38]:
A[:,:,None].shape

(3, 4, 1)

In [39]:
A[:,None,:] # лист из 3 объектов размера 4 x 1 

array([[[ 1.14582581, -1.14940945, -0.49673539, -1.47854015]],

       [[ 0.50301409, -1.50003522, -0.40356792,  0.9798549 ]],

       [[ 1.27464156, -0.83881745, -0.4142402 , -1.17077428]]])

In [40]:
A[:,None,:].shape

(3, 1, 4)

In [35]:
B.shape

(3, 4)

In [44]:
np.sqrt(np.sum((A[:,None,:] - B)**2, axis=2))

array([[2.27521269, 3.32177682, 2.86361737],
       [2.06176145, 2.22928428, 2.94694486],
       [1.83870171, 3.12866945, 2.52521895]])

In [45]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.27521269, 2.22928428, 2.52521895])