In [1]:
# Киллер правила
# 
# 100 человек, каждый одновременно чья-то жертва и чей-то убийца  
# у каждого человека в конверте имя 
#
#  Филипп -> Паша -> Лера -> Саша -> Филипп
#  Филипп -> Лера -> Саша -> Филипп

# Устные вопросов:
#
# Сколько всего раздач конвертов существует? 
# Ответ: 100! = 100 * 99 * 98 * 97 * ... * 3 * 2 * 1
#
# Какова вероятность, что Паша получит конверт с самим собой при раздаче? 
# Ответ: 99!/100! = 1/100
#
# P(Лера получила конверт с собой)
# Ответ: 1/100
#
# P(Лера и Паша суицидники) = 98!/100! = 1/99* 1/100
# 1 2 | 98!
#
# Лера <---> Паша
#
# X - количество суицидников E(X) - ? 
# Y - количество мэтчингов   E(Y) - ?
# Z - сколько жертв убил победитель E(Z) - ?

## 1. Тут мы смотрим на функции из numpy

In [2]:
import numpy as np

In [3]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In [4]:
2*x

[1, 2, 3, 1, 2, 3]

In [5]:
x*y

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
xx = np.array(x)
yy = np.array(y)
yy

array([4, 5, 6])

In [9]:
xx

array([1, 2, 3])

In [7]:
xx + yy

array([5, 7, 9])

In [10]:
3**xx

array([ 3,  9, 27])

In [11]:
xx * yy

array([ 4, 10, 18])

In [13]:
xx @ yy

32

In [14]:
np.sum(xx * yy)

32

In [16]:
np.sum(xx)

6

In [17]:
xx.sum()

6

In [19]:
xx.size

3

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.random.shuffle(x)
x

array([9, 6, 7, 4, 0, 1, 5, 8, 3, 2])

In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
xx.mean()

2.0

In [112]:
zz = np.arange(100)
zz.std()

28.86607004772212

In [113]:
zz.mean()

49.5

In [114]:
zz.var()

833.25

In [115]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
np.random.choice(zz)

91

## 2. Тут мы говорим про ООП

In [ ]:
# model = LinearRegression()
# model.fit(X, y)
# model.predict(X_test)

In [ ]:
# model_v2 = LinearRegression()
# model_v2.fit(X_v2, y_v2)
# model_v2.predict(X_test)

In [ ]:
# зажарить(картошка)  - функция
# картошка.зажарить() - метод

In [ ]:
# pass - ключевое слово, означающее что пока что тут кода нет (заглушка)

In [163]:
class Killer:
    
    # __init__ есть в любом классе, это мето-конструктор 
    # он вызывается при создании класса 
    
    # self - ключевое слово, которое помогает классу ссылаться на
    # самого себя 
    
    def __init__(self, n, verbouse=True):
        self.n = n # константа внутри класса (атрибутами)
        self.verbouse = verbouse
        self.murder_target = np.arange(n)
        
        self.alive = np.ones(n)
        self.reward = np.zeros(n)
        
        # конструктор один раз при создании класса вызовет эту функцию
        self._create_game()
            
    def _create_game(self):
        np.random.shuffle(self.murder_target)
        
    def __repr__(self):  # описание экземпляра
        return f"Killer({self.n})"
    
    def __str__(self): # более длинное человеческое описание 
        return f"Игра в киллера на {self.n} человек"
    
    def __add__(self, other):
        n = self.n + other.n
        game = Killer(n)
        return game
    
    def is_suicide(self, i):
        return self.murder_target[i] == i
    
    def count_suicide(self):
        return np.sum(self.murder_target == np.arange(self.n))
    
    def is_matching(self, i):
        return self.murder_target[self.murder_target[i]] == i
    
    def count_matching(self):
        # задание - дописать эту функцию
        pass 

    def step(self):
        killer_index = np.random.choice(self.murder_target[self.alive == 1])
        target_index = self.murder_target[killer_index]
        
        self.alive[target_index] = 0 
        self.reward[killer_index] += 1
        
        # забрал конверт
        self.murder_target[killer_index] = self.murder_target[target_index]
        self.murder_target[target_index] = -1 # для красоты
        
        if self.verbouse:
            print(f'Свой ход делает игрок {killer_index}')
            print(self.murder_target)
            print(self.alive)
            print(self.reward)
            print(" ")

    def play_game(self):
        if self.verbouse:
            print(f'Cтартовая позиция')
            print(self.murder_target)
            print(self.alive)
            print(self.reward)
            print(" ")  
        
        while np.sum(self.alive) > 0:
            self.step()
        

In [164]:
game = Killer(10)
game

Killer(10)

In [165]:
print(game)

Игра в киллера на 10 человек


In [166]:
game.play_game()

Cтартовая позиция
[7 8 2 0 4 5 9 3 6 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 
Свой ход делает игрок 6
[ 7  8  2  0  4  5  1  3  6 -1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 
Свой ход делает игрок 6
[ 7 -1  2  0  4  5  8  3  6 -1]
[1. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 
Свой ход делает игрок 5
[ 7 -1  2  0  4 -1  8  3  6 -1]
[1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 1. 2. 0. 0. 0.]
 
Свой ход делает игрок 0
[ 3 -1  2  0  4 -1  8 -1  6 -1]
[1. 0. 1. 1. 1. 0. 1. 0. 1. 0.]
[1. 0. 0. 0. 0. 1. 2. 0. 0. 0.]
 
Свой ход делает игрок 2
[ 3 -1 -1  0  4 -1  8 -1  6 -1]
[1. 0. 0. 1. 1. 0. 1. 0. 1. 0.]
[1. 0. 1. 0. 0. 1. 2. 0. 0. 0.]
 
Свой ход делает игрок 4
[ 3 -1 -1  0 -1 -1  8 -1  6 -1]
[1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[1. 0. 1. 0. 1. 1. 2. 0. 0. 0.]
 
Свой ход делает игрок 0
[ 0 -1 -1 -1 -1 -1  8 -1  6 -1]
[1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
[2. 0. 1. 0. 1. 1. 2. 0. 0. 0.]
 
Свой ход делает игрок 8
[ 0 -1 -1 -1 -1 

In [167]:
game1 = Killer(5)
game1

Killer(5)

In [168]:
game2 = Killer(7)
game2

Killer(7)

In [169]:
game = game1 + game2 
game

Killer(12)

In [170]:
game1

Killer(5)

In [103]:
n_obs = 10**5
np.mean([Killer(100).count_suicide() for i in range(n_obs)]) # оценка E(X)

1.00231

In [151]:
n_obs = 10**5

rewards = np.zeros(n_obs)
for i in range(n_obs):
    game = Killer(100, verbouse=False)
    game.play_game()
    rewards[i] = game.reward.max()

In [153]:
rewards.mean()

6.71347

In [ ]:
# Ещё вопросы: 
#
# Математическое ожидание числа цепочек в игре
#
# Математическое ожидание максимально длинной цепочки
# 
# Поменялись правила игры! Если возникает мэтчинг или суицид,
# мы случайно меняем конверты между двумя людьми при суициде 
# и между 4 людьми при мэтчинге. Математическое ожидание числа таких обменов.


In [ ]:
#[1, 0, 3, 4, 2]   # 2 цепи: 
                   # 1 -> 0 -> 1 
                   # 2 -> 3 -> 4 -> 2

In [ ]:
# Что можно поделать? 

# Есть необязательный контест про матрицу
# Есть необязательный контест про numpy

# Можно реализовать свой класс для комплексного числа 
# https://github.com/hse-econ-data-science/eds_spring_2020/blob/master/sem04_class/sem_04_181.py
# https://github.com/hse-econ-data-science/eds_spring_2020/blob/master/sem04_class/sem_04_182.py

# Можно почитать про классы семинар с ИАД
# https://github.com/hse-ds/iad-intro-ds/blob/master/2021/seminars/sem04_oop.ipynb

# Можно попробовать написать класс для отеля (второй файл - решение)
# https://github.com/hse-econ-data-science/eds_spring_2020/blob/master/sem04_class/Classes.ipynb
# https://github.com/hse-econ-data-science/eds_spring_2020/blob/master/sem04_class/Classes_solved_BEC1813-1814.ipynb


# Про магические методы __smth__
# https://proproprogs.ru/python_oop/metody-sravneniy-eq-ne-lt-gt