## Семинар №1: Случайные величины в Python

- **Случайная величина** – вопрос, который вас интересует. Абстракция, которая имеет значения и вероятности этих значений.

Непрерывные и дискретные случайные величины.

Распределение случайной величины. У непрерывных: плотность и функция распределения. У дискретных: функция, таблица распределения. 

Характеристики случайных величин. $E(X)$, $Var(X)$, $Cov(X, Y)$

## История №1: Симуляции

1. Моделируете игру
2. Играете в эту игру кучу раз и считаете статистику (вероятность, мат. ожидание, ...)

### Задача №1: Монетки

In [1]:
import numpy as np

In [13]:
def game():    
    oleg_coin = np.random.choice([1, 0], size=1, p=[0.6, 0.4])[0]
    miron_coin = np.random.choice([1, 0], size=1, p=[0.4, 0.6])[0]

    oleg_cnt = 1
    while oleg_coin != 1:
        oleg_coin = np.random.choice([1, 0], size=1, p=[0.6, 0.4])[0]
        oleg_cnt += 1

    miron_cnt = 1
    while miron_coin != 1:
        miron_coin = np.random.choice([1, 0], size=1, p=[0.4, 0.6])[0]
        miron_cnt += 1
        
        
    return oleg_cnt, miron_cnt

In [18]:
n = 10000

m = 0
for _ in range(n):
    oleg_m, miron_m = game()
    if oleg_m > miron_m:
        m += 1

$$
P = \frac{m}{n}
$$

In [19]:
m / n

0.2179

### Лирическое отступление про списки

In [25]:
a = [1, 2, 10, 20]

a + 20

TypeError: can only concatenate list (not "int") to list

Все операции в numpy.array __векторизованные__

In [27]:
a = np.array([1, 2, 10, 20])

a * 20

array([ 20,  40, 200, 400])

### Задача №2: Про удава

In [63]:
def game(baget):
    ukus_cnt = 0
    
    while baget > 0:
        ukus = np.random.random() # случайное число от 0 до 1
        baget -= ukus

        ukus_cnt += 1
        
    return ukus_cnt

In [64]:
baget = 1

n = 1000

ukus_all = []
for _ in range(n):
    ukus = game(baget)
    ukus_all.append(ukus)

In [65]:
np.mean(ukus_all)

2.734

In [66]:
np.var(ukus_all)

0.7272439999999999

## История №2: Генерация случайных величин в Python

In [67]:
from scipy import stats as sts

In [69]:
norm_gen = sts.norm(0, 1) # 0 - mu, 1 - sigma

In [73]:
norm_gen.rvs(10)

array([-0.03251858,  0.76851711, -0.7756331 , -1.00095374, -2.29852082,
        0.58735401,  1.00989237, -0.55123904,  1.28402041, -0.57684983])

In [74]:
unf_gen = sts.uniform(2, 4) # отрезок от 2 до 6

In [75]:
unf_gen.rvs(10)

array([4.89595269, 2.93609737, 3.12539213, 2.38505402, 2.96118011,
       2.56418234, 5.55365537, 3.65996483, 3.80211613, 4.07977028])

$$
F_X(x) = P(X \le x)
$$

In [76]:
norm_gen.cdf(1)

0.8413447460685429

In [77]:
norm_gen.pdf(1)

0.24197072451914337

In [80]:
norm_gen.ppf(0.8413447460685429)

1.0