# Генерация случайных величин в Python

- __Случайная величина__ – абстракция, которая имеет некоторое множество значений (исходов) и каждый из этих исходов реализуется с какой-то вероятностью.

1. Непрерывные и дискретные
2. Распределение: функцией распределения и плотностью (если непрерывные) и таблицей (если дискретные)
3. Характеристики: мат. ожидания, дисперсии, ковариации, корреляции и так далее

## История №1: Решение тервер задач с помощью симуляций

In [1]:
import numpy as np

1. __Моделируете игру__
2. __Запускаете игру__ кучу раз и считаете нужную выборочную статистику (вероятность, мат. ожидание и так далее)

### Задача №1: Монетки

In [24]:
def game():
    oleg_coin = np.random.choice([0, 1], size=1, p=[0.4, 0.6])[0]
    miron_coin = np.random.choice([0, 1], size=1, p=[0.6, 0.4])[0]

    oleg_cnt = 1
    while oleg_coin != 1:
        oleg_coin = np.random.choice([0, 1], size=1, p=[0.4, 0.6])[0]
        oleg_cnt += 1

    miron_cnt = 1
    while miron_coin != 1:
        miron_coin = np.random.choice([0, 1], size=1, p=[0.6, 0.4])[0]
        miron_cnt += 1


    return oleg_cnt, miron_cnt

In [32]:
n = 10000

m = 0
for _ in range(n):
    oleg_cnt, miron_cnt = game()
    if oleg_cnt > miron_cnt:
        m += 1

In [33]:
m / n

0.2105

$$
P = \frac{m}{n}
$$

### Задача №2: Удавы и багеты

In [54]:
def game(baget):
    ukus_cnt = 0
    
    while baget > 0:
        ukus = np.random.random() # случайное число от 0 до 1
        baget -= ukus
        ukus_cnt += 1
        
        
    return ukus_cnt

In [55]:
n = 10000

ukus_all = []
for _ in range(n):
    ukus = game(1)
    ukus_all.append(ukus)

$$
\bar x \rightarrow E(X)
$$

$$
\widehat{Var}(X) \rightarrow Var(X)
$$

In [56]:
np.mean(ukus_all)

2.7025

In [57]:
np.var(ukus_all)

0.7509937499999999

## История №2: Генерация случайных величин из разных распределений

In [58]:
from scipy import stats as sts

In [60]:
norm_gen = sts.norm(0, 1) # 0 - mu, 1 - sigma

In [61]:
norm_gen.rvs(10)

array([-1.77193402, -0.35799284,  0.36878761, -0.88776408, -0.36779173,
       -1.758996  , -0.49230064, -0.99088711, -0.28513727,  0.33440925])

In [62]:
unf_gen = sts.uniform(2, 4) # начало отрезка, длина отрезка, отрезок от 2 до 6

In [63]:
unf_gen.rvs(10)

array([3.40352303, 3.02675627, 3.36864414, 3.32673781, 5.43042651,
       5.30529368, 5.2154453 , 3.11234105, 3.89979721, 3.24220225])

$$
F_X(x) = P(X \le x)
$$

In [64]:
norm_gen.cdf(1) # функция распределения

0.8413447460685429

In [65]:
norm_gen.pdf(1) # плотность распределения

0.24197072451914337

In [66]:
norm_gen.ppf(0.01) # квантиль

-2.3263478740408408

In [67]:
norm_gen.ppf(0.8413447460685429)

1.0

### Задача №5

In [78]:
norm_gen = sts.norm(0, 3**(1/2))

n = 1000
norm_sample = norm_gen.rvs(n)

Операции в нумпаевских массивах __векторизованны__

In [79]:
a = [1, 2, 3]

a + 20

TypeError: can only concatenate list (not "int") to list

In [80]:
a = np.array([1, 2, 3])

a * 20

array([20, 40, 60])

$$
X
$$

In [81]:
norm_sample[:10]

array([ 0.90413891,  1.69924267,  0.70892619, -3.90428311, -1.55299916,
       -1.31240622,  0.55024809, -0.50005206, -1.90452405, -2.32119482])

$$
Y = \frac{1}{X}
$$

In [82]:
Y = 1 / norm_sample

$$
E(Y) = E(\frac{1}{X})
$$

In [77]:
np.mean(Y)

-0.009923438546868965

In [99]:
norm_gen = sts.norm(1, 3**(1/2))

n = 10000
norm_sample = norm_gen.rvs(n)

Y = 1 / norm_sample
np.mean(Y)

-0.28310565862658693